config setup

conn sede-central
    keyexchange=ikev2
    ike=aes256-sha256-x25519-ke1_mlkem768!
    esp=aes256gcm16
    authby=rsasig

conn proveedor-antiguo
    keyexchange=ikev1
    ike=3des-sha1-modp1024,aes128-sha256-modp2048
    esp=aes128-sha1
    authby=psk
