# Aplicación interna
<VirtualHost *:443>
    ServerName intranet.ejemplo.test
    SSLEngine on
    SSLProtocol all -SSLv3 -TLSv1
    SSLCipherSuite HIGH:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA:TLS_RSA_WITH_AES_128_CBC_SHA
    SSLCertificateFile /etc/ssl/intranet.crt
</VirtualHost>
